/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kalkulatorsederhana;

import java.awt.Color;

/**
 *
 * @author AhmadFaruq
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    float angka_1 = 0;
    float angka_2 = 0;
    String operator;
    
    float kalkulator(float angka_1, String operator, float angka_2){
        
        switch(operator){
            case "+": return angka_1 + angka_2;
            case "-": return angka_1 - angka_2;
            case "x": return angka_1 * angka_2;
            case "/": return angka_1 / angka_2;
                
        }
        return 0;
    }
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbl7 = new javax.swing.JLabel();
        tbl8 = new javax.swing.JLabel();
        tbl9 = new javax.swing.JLabel();
        tbl4 = new javax.swing.JLabel();
        tbl5 = new javax.swing.JLabel();
        tbl6 = new javax.swing.JLabel();
        tbl1 = new javax.swing.JLabel();
        tbl2 = new javax.swing.JLabel();
        tbl3 = new javax.swing.JLabel();
        tbl0 = new javax.swing.JLabel();
        tblkoma = new javax.swing.JLabel();
        tblx = new javax.swing.JLabel();
        tblkrg = new javax.swing.JLabel();
        tbltmbh = new javax.swing.JLabel();
        tblhsl = new javax.swing.JLabel();
        tblclr = new javax.swing.JLabel();
        tblbagi = new javax.swing.JLabel();
        tblhps = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tampilan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tblhps1 = new javax.swing.JLabel();
        tblhps2 = new javax.swing.JLabel();
        tblhps3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl7.setBackground(new java.awt.Color(0, 0, 0));
        tbl7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbl7.setForeground(new java.awt.Color(255, 255, 255));
        tbl7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl7.setText("7");
        tbl7.setOpaque(true);
        tbl7.setPreferredSize(new java.awt.Dimension(30, 30));
        tbl7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl7MouseReleased(evt);
            }
        });
        getContentPane().add(tbl7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 50, 50));

        tbl8.setBackground(new java.awt.Color(0, 0, 0));
        tbl8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbl8.setForeground(new java.awt.Color(255, 255, 255));
        tbl8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl8.setText("8");
        tbl8.setOpaque(true);
        tbl8.setPreferredSize(new java.awt.Dimension(30, 30));
        tbl8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl8MouseReleased(evt);
            }
        });
        getContentPane().add(tbl8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 50, 50));

        tbl9.setBackground(new java.awt.Color(0, 0, 0));
        tbl9.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbl9.setForeground(new java.awt.Color(255, 255, 255));
        tbl9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl9.setText("9");
        tbl9.setOpaque(true);
        tbl9.setPreferredSize(new java.awt.Dimension(30, 30));
        tbl9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl9MouseReleased(evt);
            }
        });
        getContentPane().add(tbl9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 50, 50));

        tbl4.setBackground(new java.awt.Color(0, 0, 0));
        tbl4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbl4.setForeground(new java.awt.Color(255, 255, 255));
        tbl4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl4.setText("4");
        tbl4.setOpaque(true);
        tbl4.setPreferredSize(new java.awt.Dimension(30, 30));
        tbl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl4MouseReleased(evt);
            }
        });
        getContentPane().add(tbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 50, 50));

        tbl5.setBackground(new java.awt.Color(0, 0, 0));
        tbl5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbl5.setForeground(new java.awt.Color(255, 255, 255));
        tbl5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl5.setText("5");
        tbl5.setOpaque(true);
        tbl5.setPreferredSize(new java.awt.Dimension(30, 30));
        tbl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl5MouseReleased(evt);
            }
        });
        getContentPane().add(tbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 50, 50));

        tbl6.setBackground(new java.awt.Color(0, 0, 0));
        tbl6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbl6.setForeground(new java.awt.Color(255, 255, 255));
        tbl6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl6.setText("6");
        tbl6.setOpaque(true);
        tbl6.setPreferredSize(new java.awt.Dimension(30, 30));
        tbl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl6MouseReleased(evt);
            }
        });
        getContentPane().add(tbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 50, 50));

        tbl1.setBackground(new java.awt.Color(0, 0, 0));
        tbl1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbl1.setForeground(new java.awt.Color(255, 255, 255));
        tbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl1.setText("1");
        tbl1.setOpaque(true);
        tbl1.setPreferredSize(new java.awt.Dimension(30, 30));
        tbl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl1MouseReleased(evt);
            }
        });
        getContentPane().add(tbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 50, 50));

        tbl2.setBackground(new java.awt.Color(0, 0, 0));
        tbl2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbl2.setForeground(new java.awt.Color(255, 255, 255));
        tbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl2.setText("2");
        tbl2.setOpaque(true);
        tbl2.setPreferredSize(new java.awt.Dimension(30, 30));
        tbl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl2MouseReleased(evt);
            }
        });
        getContentPane().add(tbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 50, 50));

        tbl3.setBackground(new java.awt.Color(0, 0, 0));
        tbl3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbl3.setForeground(new java.awt.Color(255, 255, 255));
        tbl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl3.setText("3");
        tbl3.setOpaque(true);
        tbl3.setPreferredSize(new java.awt.Dimension(30, 30));
        tbl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl3MouseReleased(evt);
            }
        });
        getContentPane().add(tbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 50, 50));

        tbl0.setBackground(new java.awt.Color(0, 0, 0));
        tbl0.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbl0.setForeground(new java.awt.Color(255, 255, 255));
        tbl0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbl0.setText("0");
        tbl0.setOpaque(true);
        tbl0.setPreferredSize(new java.awt.Dimension(30, 30));
        tbl0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl0MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbl0MouseReleased(evt);
            }
        });
        getContentPane().add(tbl0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 50, 50));

        tblkoma.setBackground(new java.awt.Color(0, 0, 0));
        tblkoma.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblkoma.setForeground(new java.awt.Color(255, 255, 255));
        tblkoma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblkoma.setText(".");
        tblkoma.setOpaque(true);
        tblkoma.setPreferredSize(new java.awt.Dimension(30, 30));
        tblkoma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblkomaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblkomaMouseReleased(evt);
            }
        });
        getContentPane().add(tblkoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 50, 50));

        tblx.setBackground(new java.awt.Color(0, 0, 0));
        tblx.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblx.setForeground(new java.awt.Color(255, 102, 0));
        tblx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblx.setText("×");
        tblx.setOpaque(true);
        tblx.setPreferredSize(new java.awt.Dimension(30, 30));
        tblx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblxMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblxMouseReleased(evt);
            }
        });
        getContentPane().add(tblx, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 50, 50));

        tblkrg.setBackground(new java.awt.Color(0, 0, 0));
        tblkrg.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblkrg.setForeground(new java.awt.Color(255, 102, 0));
        tblkrg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblkrg.setText("-");
        tblkrg.setOpaque(true);
        tblkrg.setPreferredSize(new java.awt.Dimension(30, 30));
        tblkrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblkrgMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblkrgMouseReleased(evt);
            }
        });
        getContentPane().add(tblkrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 50, 50));

        tbltmbh.setBackground(new java.awt.Color(0, 0, 0));
        tbltmbh.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tbltmbh.setForeground(new java.awt.Color(255, 102, 0));
        tbltmbh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tbltmbh.setText("+");
        tbltmbh.setOpaque(true);
        tbltmbh.setPreferredSize(new java.awt.Dimension(30, 30));
        tbltmbh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbltmbhMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tbltmbhMouseReleased(evt);
            }
        });
        getContentPane().add(tbltmbh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 50, 50));

        tblhsl.setBackground(new java.awt.Color(0, 0, 0));
        tblhsl.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblhsl.setForeground(new java.awt.Color(255, 102, 0));
        tblhsl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblhsl.setText("=");
        tblhsl.setOpaque(true);
        tblhsl.setPreferredSize(new java.awt.Dimension(30, 30));
        tblhsl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblhslMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblhslMouseReleased(evt);
            }
        });
        getContentPane().add(tblhsl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 50, 50));

        tblclr.setBackground(new java.awt.Color(0, 0, 0));
        tblclr.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblclr.setForeground(new java.awt.Color(255, 102, 0));
        tblclr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblclr.setText("AC");
        tblclr.setOpaque(true);
        tblclr.setPreferredSize(new java.awt.Dimension(30, 30));
        tblclr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblclrMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblclrMouseReleased(evt);
            }
        });
        getContentPane().add(tblclr, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 50, 50));

        tblbagi.setBackground(new java.awt.Color(0, 0, 0));
        tblbagi.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblbagi.setForeground(new java.awt.Color(255, 102, 0));
        tblbagi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblbagi.setText("÷");
        tblbagi.setOpaque(true);
        tblbagi.setPreferredSize(new java.awt.Dimension(30, 30));
        tblbagi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblbagiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblbagiMouseReleased(evt);
            }
        });
        getContentPane().add(tblbagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, 50));

        tblhps.setBackground(new java.awt.Color(0, 0, 0));
        tblhps.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblhps.setForeground(new java.awt.Color(255, 102, 0));
        tblhps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblhps.setText("DEL");
        tblhps.setOpaque(true);
        tblhps.setPreferredSize(new java.awt.Dimension(30, 30));
        tblhps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblhpsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblhpsMouseReleased(evt);
            }
        });
        getContentPane().add(tblhps, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 50, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("------------------------------------------------------");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        tampilan.setBackground(new java.awt.Color(0, 0, 0));
        tampilan.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tampilan.setForeground(new java.awt.Color(255, 255, 255));
        tampilan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tampilan.setOpaque(true);
        getContentPane().add(tampilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 44, 210, 40));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setText(".");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 350));

        tblhps1.setBackground(new java.awt.Color(0, 0, 0));
        tblhps1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblhps1.setForeground(new java.awt.Color(255, 102, 0));
        tblhps1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblhps1.setText("DEL");
        tblhps1.setOpaque(true);
        tblhps1.setPreferredSize(new java.awt.Dimension(30, 30));
        tblhps1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblhps1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblhps1MouseReleased(evt);
            }
        });
        getContentPane().add(tblhps1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 50, 50));

        tblhps2.setBackground(new java.awt.Color(0, 0, 0));
        tblhps2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblhps2.setForeground(new java.awt.Color(255, 102, 0));
        tblhps2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblhps2.setText("DEL");
        tblhps2.setOpaque(true);
        tblhps2.setPreferredSize(new java.awt.Dimension(30, 30));
        tblhps2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblhps2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblhps2MouseReleased(evt);
            }
        });
        getContentPane().add(tblhps2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 50, 50));

        tblhps3.setBackground(new java.awt.Color(0, 0, 0));
        tblhps3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        tblhps3.setForeground(new java.awt.Color(255, 102, 0));
        tblhps3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tblhps3.setText("DEL");
        tblhps3.setOpaque(true);
        tblhps3.setPreferredSize(new java.awt.Dimension(30, 30));
        tblhps3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblhps3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblhps3MouseReleased(evt);
            }
        });
        getContentPane().add(tblhps3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl7MouseClicked

    private void tbl7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl7MousePressed
        tbl7.setBackground(new Color(81,81,81));
        tampilan.setText(tampilan.getText()+"7");
    }//GEN-LAST:event_tbl7MousePressed

    private void tbl7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl7MouseReleased
        tbl7.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tbl7MouseReleased

    private void tbl8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl8MousePressed
        tbl8.setBackground(new Color(81,81,81));
        tampilan.setText(tampilan.getText()+"8");
    }//GEN-LAST:event_tbl8MousePressed

    private void tbl8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl8MouseReleased
        tbl8.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tbl8MouseReleased

    private void tbl9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl9MousePressed
        tbl9.setBackground(new Color(81,81,81));
        tampilan.setText(tampilan.getText()+"9");
    }//GEN-LAST:event_tbl9MousePressed

    private void tbl9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl9MouseReleased
        tbl9.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tbl9MouseReleased

    private void tbl4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl4MousePressed
        tbl4.setBackground(new Color(81,81,81));
        tampilan.setText(tampilan.getText()+"4");
    }//GEN-LAST:event_tbl4MousePressed

    private void tbl4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl4MouseReleased
        tbl4.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tbl4MouseReleased

    private void tbl5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl5MousePressed
        tbl5.setBackground(new Color(81,81,81));
        tampilan.setText(tampilan.getText()+"5");
    }//GEN-LAST:event_tbl5MousePressed

    private void tbl5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl5MouseReleased
        tbl5.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tbl5MouseReleased

    private void tbl6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl6MousePressed
        tbl6.setBackground(new Color(81,81,81));
        tampilan.setText(tampilan.getText()+"6");
    }//GEN-LAST:event_tbl6MousePressed

    private void tbl6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl6MouseReleased
        tbl6.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tbl6MouseReleased

    private void tbl1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MousePressed
        tbl1.setBackground(new Color(81,81,81));
        tampilan.setText(tampilan.getText()+"1");
    }//GEN-LAST:event_tbl1MousePressed

    private void tbl1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl1MouseReleased
        tbl1.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tbl1MouseReleased

    private void tbl2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MousePressed
        tbl2.setBackground(new Color(81,81,81));
        tampilan.setText(tampilan.getText()+"2");
    }//GEN-LAST:event_tbl2MousePressed

    private void tbl2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl2MouseReleased
        tbl2.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tbl2MouseReleased

    private void tbl3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl3MousePressed
        tbl3.setBackground(new Color(81,81,81));
        tampilan.setText(tampilan.getText()+"3");
    }//GEN-LAST:event_tbl3MousePressed

    private void tbl3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl3MouseReleased
        tbl3.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tbl3MouseReleased

    private void tbl0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl0MousePressed
        tbl0.setBackground(new Color(81,81,81));
        tampilan.setText(tampilan.getText()+"0");
    }//GEN-LAST:event_tbl0MousePressed

    private void tbl0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl0MouseReleased
        tbl0.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tbl0MouseReleased

    private void tblkomaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkomaMousePressed
        tblkoma.setBackground(new Color(81,81,81));
        tampilan.setText(tampilan.getText()+".");
    }//GEN-LAST:event_tblkomaMousePressed

    private void tblkomaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkomaMouseReleased
        tblkoma.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tblkomaMouseReleased

    private void tblhslMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhslMousePressed
        tblhsl.setBackground(new Color(81,81,81));
        angka_2 = Float.valueOf(tampilan.getText());
        float hasil = kalkulator(angka_1,operator,angka_2);
        tampilan.setText(String.valueOf(hasil));
    }//GEN-LAST:event_tblhslMousePressed

    private void tblhslMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhslMouseReleased
        tblhsl.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tblhslMouseReleased

    private void tbltmbhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltmbhMousePressed
        tbltmbh.setBackground(new Color(81,81,81));
        angka_1 = Float.valueOf(tampilan.getText());
        operator="+";        
        tampilan.setText("");
    }//GEN-LAST:event_tbltmbhMousePressed

    private void tbltmbhMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltmbhMouseReleased
        tbltmbh.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tbltmbhMouseReleased

    private void tblkrgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkrgMousePressed
        tblkrg.setBackground(new Color(81,81,81));
        angka_1 = Float.valueOf(tampilan.getText());
        operator="-";
        tampilan.setText("");
        
    }//GEN-LAST:event_tblkrgMousePressed

    private void tblkrgMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblkrgMouseReleased
        tblkrg.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tblkrgMouseReleased

    private void tblxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblxMousePressed
        tblx.setBackground(new Color(81,81,81));
        angka_1 = Float.valueOf(tampilan.getText());
        operator="x";
        tampilan.setText("");
    }//GEN-LAST:event_tblxMousePressed

    private void tblxMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblxMouseReleased
        tblx.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tblxMouseReleased

    private void tblbagiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbagiMousePressed
        tblbagi.setBackground(new Color(81,81,81));
        angka_1 = Float.valueOf(tampilan.getText());
        operator="/";
        tampilan.setText("");

    }//GEN-LAST:event_tblbagiMousePressed

    private void tblbagiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbagiMouseReleased
        tblbagi.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tblbagiMouseReleased

    private void tblhpsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhpsMousePressed
        tblhps.setBackground(new Color(81,81,81));
        String text=tampilan.getText();
        tampilan.setText(text.substring(0,text.length()-1));
        
    }//GEN-LAST:event_tblhpsMousePressed

    private void tblhpsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhpsMouseReleased
        tblhps.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tblhpsMouseReleased

    private void tblclrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblclrMousePressed
        tblclr.setBackground(new Color(81,81,81));
        tampilan.setText("");
    }//GEN-LAST:event_tblclrMousePressed

    private void tblclrMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblclrMouseReleased
        tblclr.setBackground(new Color(0,0,0));
    }//GEN-LAST:event_tblclrMouseReleased

    private void tblhps1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhps1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblhps1MousePressed

    private void tblhps1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhps1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblhps1MouseReleased

    private void tblhps2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhps2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblhps2MousePressed

    private void tblhps2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhps2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblhps2MouseReleased

    private void tblhps3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhps3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblhps3MousePressed

    private void tblhps3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhps3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tblhps3MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel tampilan;
    private javax.swing.JLabel tbl0;
    private javax.swing.JLabel tbl1;
    private javax.swing.JLabel tbl2;
    private javax.swing.JLabel tbl3;
    private javax.swing.JLabel tbl4;
    private javax.swing.JLabel tbl5;
    private javax.swing.JLabel tbl6;
    private javax.swing.JLabel tbl7;
    private javax.swing.JLabel tbl8;
    private javax.swing.JLabel tbl9;
    private javax.swing.JLabel tblbagi;
    private javax.swing.JLabel tblclr;
    private javax.swing.JLabel tblhps;
    private javax.swing.JLabel tblhps1;
    private javax.swing.JLabel tblhps2;
    private javax.swing.JLabel tblhps3;
    private javax.swing.JLabel tblhsl;
    private javax.swing.JLabel tblkoma;
    private javax.swing.JLabel tblkrg;
    private javax.swing.JLabel tbltmbh;
    private javax.swing.JLabel tblx;
    // End of variables declaration//GEN-END:variables
}
